# Generated by Django 4.2.6 on 2023-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoModelsToshiba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toshiba',
            name='phone',
            field=models.ImageField(max_length=5, null=True, upload_to=''),
        ),
    ]
